### ISSUE TITLE
Code duplication

### ISSUE THREAD

**Issue by butschster** [fuko-php/masked#3]
Hi. I've scrutinized your code and have notice several code block with similar code. For instance:

This method hides values from array https://github.com/fuko-php/masked/blob/master/src/Protect.php#L44 and you have also method `hideValue` that does the same work.
And your `hideValues` could look like this
```php
public static function hideValues(array $values)
{
   foreach ($values as $value){
      self::hideValue($value);
   }
}
``` 

The same problem also is here: https://github.com/fuko-php/masked/blob/master/src/Protect.php#L185

```php
foreach ($names as $name)
{
   self::hideInput($name, $type);
}
```

**Comment by kktsvetkov** [comment]
Thanks for the feedback. It was deliberately done this way to accommodate different error messages for  the "plural" methods.

**Comment by butschster** [comment]
This messages can be avoid. You can write good manual and php docs instead of duplicate code because of different messages. Nobody needs this messages. Try to find similar messages in other projects.

**Comment by kktsvetkov** [comment]
I must disagree. Error messages are instantly seen when something goes wrong, while reading the docs requires extra effort to find the docs, locate the portion of them related to your problem and figure out what is going on. 

Good error messages improve the code usability. More people will read the error messages than the documentation.
