### ISSUE TITLE
Constant FILTER_SANITIZE_STRING is deprecated 

### ISSUE THREAD

**Issue by bynicolas** [fuko-php/masked#5]
the use of `FILTER_SANITIZE_STRING` is deprecated since PHP 8.1.0.

this is used twice in `fuko-php/masked/src/Masked/Redact.php` on line `107` and `109`.

the use of `htmlspecialchars()` instead is encouraged.

This needs to be updated in the code.

**Comment by kktsvetkov** [comment]
Issue is addressed in 7c106fe
